---
title: "Exercises to Accompany TeachingWithR Workshop"
subtitle: "2021 US Conference on Teaching Statistics"
author: "Matthew Beckman & Justin Post"
date: "June 25, 2021"
output:
  github_document:
    df_print: paged
---


# Part 1. RStudio IDE Scavenger Hunt

<hr>

## 1.1 RStudio GUI 

**Task:** Search the menus in your RStudio IDE to locate where each of the following can be accomplished: 

1. Restart your R Session
#. Create a new "R Markdown" file 
#. Install `lubridate` packages (with dependencies if needed)
#. search the Help to learn about the "head" function
#. What types of data sources can be imported using the RStudio GUI

<hr>

### Solution

1. RStudio >> Session 
#. RStudio >> File >> New File >> R Markdown
#. RStudio >> Packages >> Install >> [type the package name in the search bar]
#. RStudio >> Help >> [type "head" in search bar]
#. RStudio >> File >> Import Dataset 

<hr>


## 1.2 Configuration Details Handy for Teaching

**Task:** Visit "RStudio >> Tools >> Global Options" and locate the following: 

1. Pane Layout
#. "Rainbow parenthesis"
#. "Show margin" (set to 80)
#. "Highlight selected line"
#. "Provide R style diagnostics (e.g., whitespace)"
#. "Show whitespace characters" 

<hr>

### Solution

1. Tools >> Global Options >> Pane Layout (in left-side navigation)
#. Tools >> Global Options >> Code >> Display 
#. Tools >> Global Options >> Code >> Display
#. Tools >> Global Options >> Code >> Display
#. Tools >> Global Options >> Code >> Diagnostics
#. Tools >> Global Options >> Code >> Display

<hr>


<br>

<a href = "https://jbpost2.github.io/TeachingWithR/CourseFiles.html"><button type="button">Course Files Page</button></a> 


